#!/usr/bin/env python3
"""Makes cards with the real Python tools and writes them as a C++ header for card_codec_test.cpp: python3 gen_card_fixture.py OUT.h"""
import os
import sys

sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "..", "scripts"))
import card_format  # noqa: E402
from cryptography.hazmat.primitives import serialization  # noqa: E402
from cryptography.hazmat.primitives.asymmetric import ec  # noqa: E402

BOX = "aabbccddeeff"
OTHER_BOX = "112233445566"
key = ec.generate_private_key(ec.SECP256R1())
other = ec.generate_private_key(ec.SECP256R1())
der = key.public_key().public_bytes(serialization.Encoding.DER, serialization.PublicFormat.SubjectPublicKeyInfo)

good = card_format.encode(key, BOX, 42, 10800)
cards = {
    "GOOD": good,
    "GOOD_MAX_SERIAL": card_format.encode(key, BOX, 65535, 10800),
    "GOOD_5H": card_format.encode(key, BOX, 7, 18000),
    "OTHER_BOX": card_format.encode(key, OTHER_BOX, 42, 10800),
    "OTHER_KEY": card_format.encode(other, BOX, 42, 10800),
    "BAD_SERIAL": good.replace(".42.", ".43."),
    "BAD_SECONDS": good.replace(".10800.", ".99999."),
}
with open(sys.argv[1], "w") as f:
    f.write("// generated by gen_card_fixture.py\n")
    f.write("static const uint8_t FIX_PUBKEY[] = {" + ", ".join(f"0x{b:02x}" for b in der) + "};\n")
    f.write(f'static const char* const FIX_BOX = "{BOX}";\n')
    for name, text in cards.items():
        f.write(f'static const char* const CARD_{name} = "{text}";\n')
