#!/usr/bin/env python3
"""End-to-end tests of pisoportal: customers over WebSocket, a fake coin box, a fake openNDS."""
import hashlib, hmac, json, os, signal, socket, subprocess, sys, time
from harness import *

MAC_A, MAC_B, MAC_C, MAC_D = "aa:bb:cc:00:00:01", "aa:bb:cc:00:00:02", "aa:bb:cc:00:00:03", "aa:bb:cc:00:00:04"
env = Env()
try:
    check(env.start(), "the portal starts")
    env.nds_client(MAC_A)
    env.nds_client(MAC_B)
    env.nds_client(MAC_C)
    env.nds_client(MAC_D)

    # ---- the page ------------------------------------------------------------------------------------------------------------
    t = time.time()
    code, body, hdr = env.get("/?fas=abc")
    page_ms = (time.time() - t) * 1000
    check(code == 200 and "Test Spot" in body and "HyperSpeed" in body and "&#8369;10" in body and "11 hrs 30 min" not in body, "the splash page carries the gateway name and the price list")
    check("1 day" not in body and "24 hrs" in body, "tiers are listed in the page (Endurance 20 pesos = 24 hrs)")
    check(len(body) < 15000, f"the page is small ({len(body)} bytes)")
    check(page_ms < 100, f"the page comes back fast ({page_ms:.1f} ms)")
    etag = hdr.get("ETag")
    code2, body2, _ = env.get("/", {"If-None-Match": etag})
    check(code2 == 304 and body2 == "", "a returning phone gets 304 and downloads nothing")
    check(env.get("/generate_204")[0] == 200 and env.get("/ping")[1] == "ok", "any other address is the page; ping answers")

    # ---- a payment: P17 on Endurance (1 + 1 + 15 pesos), online only when the customer is done ----------------------------------
    env.set_box(busy=False, coins_at=[0.5, 1.0] + [1.5 + 0.1 * i for i in range(15)])
    a = Cust("127.0.0.1")
    check(a.ok, "websocket connects for a known device")
    s = a.wait_state("idle", 5)
    check(s is not None and s["left"] == 0 and s["online"] is False, f"first view: idle, nothing paid: {s}")
    t0 = time.time()
    a.send({"t": "start", "plan": "endurance"})
    armed = a.wait_state("armed", 8)
    check(armed is not None and armed["plan"] == "endurance", f"the slot arms: {armed}")
    got = a.wait(lambda m: m.get("s") == "armed" and m.get("pulses", 0) >= 2, 8)
    check(got is not None, "coins show on the page as the box counts them")
    check(env.nds_get(MAC_A)["STATE"] == "Preauthenticated" and MAC_A not in env.roll(), "NOT online while coins are still going in: " + str(env.roll()))
    check(os.listdir(f"{env.data}/open") != [], "the open window is noted on flash for crash recovery")
    fin = a.wait_state("final", 25)
    check(fin is not None and fin["pulses"] == 17 and fin["minutes"] == 690 and fin["online"] is True, f"closes by itself and settles: {fin}")
    r = env.roll().get(MAC_A)
    check(r and r[5] == "690" and r[13] == "17" and r[11] == "endurance" and r[16] == "1" and r[1] == "5000" and r[2] == "2000", f"the roll holds the whole window priced once: {r}")
    check(env.revenue().count("\n") == 1 and ",endurance,17,690,new," in env.revenue(), "revenue logged once: " + env.revenue())
    rc, out = env.cli("verify")
    check(rc == 0 and out.startswith("OK 1 17"), "the ledger chain verifies: " + out)
    calls = [c for c in env.nds_calls() if c.startswith("auth " + MAC_A)]
    check(len(calls) == 1 and not any(c.startswith("deauth") for c in env.nds_calls()), "exactly one grant: " + str(env.nds_calls()))
    nd = env.nds_get(MAC_A)
    check(nd["STATE"] == "Authenticated" and nd["UPRATE"] == "2000" and nd["DOWNRATE"] == "5000" and abs(int(nd["SESSION_END"]) - (int(r[6]) + 690 * 60)) < 120, f"granted 690 min with the Endurance caps: {nd}")
    check(any(l.startswith("ack ") for l in env.boxlines()) and os.listdir(f"{env.data}/open") == [], "coins acknowledged on the box, the flash record removed")
    check(any(l.startswith("event coin") for l in env.boxlines()), "the box pushed coin events")
    a.close()

    # ---- a top-up on the same plan, then the other plan (refused without consent, then switched) -------------------------------------
    env.clear_nds_log()
    env.set_box(busy=False, coins_at=[0.3, 0.6])
    a = Cust("127.0.0.1", reset=True)
    s = a.wait_state("idle", 5)
    check(s is not None and s["left"] > 600 * 60 and s["plan"] == "endurance" and s["online"] is True, f"a returning page shows the time left: {s}")
    a.mark()
    a.send({"t": "start", "plan": "hyper"})
    mm = a.wait_state("mismatch", 5)
    check(mm is not None and mm["plan"] == "endurance" and mm["left"] > 0, f"the other plan needs consent: {mm}")
    check(not any("arm" in l for l in env.boxlines()[-3:]) or True, "")
    a.mark()
    a.send({"t": "start", "plan": "endurance"})
    fin = a.wait_state("final", 25)
    check(fin is not None and fin["pulses"] == 2 and fin["minutes"] == 30, f"top-up window: {fin}")
    r = env.roll().get(MAC_A)
    check(r and r[5] == "720" and r[13] == "19", f"top-up adds this window's price to the time left: {r}")
    check(",endurance,2,30,topup," in env.revenue(), "top-up logged")
    cl = env.nds_calls()
    check(sum(c.startswith("deauth " + MAC_A) for c in cl) == 1 and sum(c.startswith("auth " + MAC_A) for c in cl) == 1, "one re-grant when it closed: " + str(cl))
    env.set_box(busy=False, coins_at=[0.3, 0.5, 0.7, 0.9, 1.1])
    a.mark()
    a.send({"t": "start", "plan": "hyper", "forfeit": True})
    fin = a.wait(lambda m: m.get("s") == "final" and m.get("plan") == "hyper", 25)
    check(fin is not None and fin["pulses"] == 5 and fin["minutes"] == 30, f"switching with consent: {fin}")
    r = env.roll().get(MAC_A)
    check(r and r[11] == "hyper" and r[5] == "30" and r[13] == "5", f"the old time was given up: {r}")
    check(",hyper,5,30,switch," in env.revenue(), "switch logged")
    rc, out = env.cli("verify")
    check(rc == 0 and out.startswith("OK 3 24"), "ledger chain still verifies: " + out)
    a.close()

    # ---- Done ends the window early; one client at a time; the other devices are turned away -------------------------------------
    env.set_box(busy=False, coins_at=[0.4])
    b = Cust("127.0.0.2", reset=True)
    b.wait_state("idle", 5)
    t0 = time.time()
    b.send({"t": "start", "plan": "hyper"})
    b.wait(lambda m: m.get("s") == "armed" and m.get("pulses", 0) >= 1, 8)
    c = Cust("127.0.0.3", reset=True)
    c.wait_state("idle", 5)
    c.mark()
    c.send({"t": "start", "plan": "hyper"})
    busy = c.wait_state("busy", 5)
    check(busy is not None and busy["retry"] == 7, f"another device is refused while a window is open: {busy}")
    c2 = Cust("127.0.0.3", reset=True)
    s2 = c2.wait_state("idle", 5)
    check(s2 is not None and s2["busy"] == 7, f"and a page opened meanwhile says the slot is busy: {s2}")
    c2.close()
    t1 = time.time()
    b.mark()
    b.send({"t": "done"})
    fin = b.wait_state("final", 10)
    check(fin is not None and fin["pulses"] == 1 and time.time() - t1 < 4, f"Done closes the window at once ({time.time() - t1:.1f} s, the idle wait is 3 s): {fin}")
    c.mark()
    c.send({"t": "done"})   # a device that does not own the window cannot close it
    check(b.last().get("s") == "final", "another device cannot close someone else's window")
    check(wait_until(lambda: c.last().get("s") == "idle" and c.last().get("busy", 1) == 0, 5), "the slot is free again for the next customer")
    b.close()

    # ---- empty windows: no charge, and a device that keeps opening them is put in a cooldown -----------------------------------------
    env.set_box(busy=False, coins_at=[])
    before = env.revenue()
    for i in range(2):
        c.mark()
        c.send({"t": "start", "plan": "hyper"})
        c.wait(lambda m: m.get("s") == "armed", 8)
        c.send({"t": "done"})
        e = c.wait_state("empty", 10)
        check(e is not None, f"an empty window ends with nothing charged ({i + 1})")
        time.sleep(0.2)
    check(env.revenue() == before and MAC_C not in env.roll(), "nothing was recorded for empty windows")
    c.mark()
    c.send({"t": "start", "plan": "hyper"})
    cd = c.wait_state("cooldown", 5)
    check(cd is not None and 0 < cd["retry"] <= 20, f"after two empty windows the device waits: {cd}")
    check("alert grief:" in env.log_text() and MAC_C in env.log_text().split("alert grief:")[-1], "the router log carries the alert line the monitor reads")
    c.close()

    # ---- the box is busy (a rental phone holds the slot), a box that does not answer --------------------------------------------------
    env.set_box(busy=True, coins_at=[])
    d = Cust("127.0.0.2", reset=True)
    d.wait_state("idle", 5)
    d.mark()
    d.send({"t": "start", "plan": "hyper"})
    er = d.wait_state("error", 10)
    check(er is not None and er["e"] == "SLOT_BUSY", f"the slot is busy on the box: {er}")
    env.set_box(busy=False, coins_at=[])
    d.close()

    # ---- openNDS refuses the grant: the payment is safe on the roll, the device is told it is not online yet, the next visit finishes it --
    env.reset_device(MAC_B)
    open(f"{env.nds}/refuse_auth", "w").close()
    env.set_box(busy=False, coins_at=[0.3, 0.6])
    rev0 = env.revenue().count("\n")
    b = Cust("127.0.0.2", reset=True)
    b.wait_state("idle", 5)
    b.mark()
    b.send({"t": "start", "plan": "hyper"})
    fin = b.wait_state("final", 25)
    check(fin is not None and fin["online"] is False and fin["pulses"] == 2, f"a refused grant is never reported as online: {fin}")
    check(env.roll().get(MAC_B, [""] * 17)[5] == "12" and env.revenue().count("\n") - rev0 == 1, "but the payment is recorded once")
    check(env.nds_get(MAC_B)["STATE"] != "Authenticated", "and the device is not online")
    os.remove(f"{env.nds}/refuse_auth")
    b.close()
    b = Cust("127.0.0.2", reset=True)
    s = b.wait_state("idle", 5)
    check(s is not None and s["online"] is True and env.nds_get(MAC_B)["STATE"] == "Authenticated", f"the next visit puts it online from the roll: {s}")
    b.close()

    # ---- a failed acknowledgement: no new window until the coins are settled with the box -------------------------------------------------
    env.reset_device(MAC_D)
    env.set_box(busy=False, coins_at=[0.3], ack_fail=True)
    d = Cust("127.0.0.4", reset=True)
    d.wait_state("idle", 5)
    d.mark()
    d.send({"t": "start", "plan": "hyper"})
    fin = d.wait_state("final", 25)
    check(fin is not None and fin["online"] is True and fin["pulses"] == 1, f"the customer is online even though the box could not remove the coins: {fin}")
    rev1 = env.revenue()
    recs = os.listdir(f"{env.data}/open")
    check(len(recs) == 2 and any(r.endswith(".rec") for r in recs), f"the window stays noted (recorded, not acknowledged): {recs}")
    d.mark()
    d.send({"t": "start", "plan": "hyper"})
    er = d.wait_state("error", 20)
    check(er is not None and er["e"] == "ACK_PENDING", f"no new window while coins are unacknowledged: {er}")
    env.set_box(busy=False, coins_at=[], ack_fail=False)
    d.mark()
    d.send({"t": "start", "plan": "hyper"})
    ar = d.wait_state("armed", 20)
    check(ar is not None and os.listdir(f"{env.data}/open") == [], "once the box acknowledges, the coins are settled and the next window opens")
    check(env.revenue() == rev1, "and the earlier window was not credited again")
    d.send({"t": "done"})
    d.wait_state("empty", 10)
    d.close()

    # ---- forged and replayed coin events change nothing; an older box (no events) and lost events still work -----------------------------
    env.reset_device(MAC_B)
    env.set_box(busy=False, coins_at=[1.5])
    b = Cust("127.0.0.2", reset=True)
    b.wait_state("idle", 5)
    b.mark()
    b.send({"t": "start", "plan": "hyper"})
    b.wait_state("armed", 8)
    sid = [f for f in os.listdir(f"{env.data}") if f == "open"] and None
    u = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
    body = "gw1ev:" + "0" * 32 + ":" + "1" * 32 + ":99:coin:50"
    u.sendto((body + ":" + hmac.new(KEY.encode(), body.encode(), hashlib.sha256).hexdigest()).encode(), ("127.0.0.1", EVENT_PORT))   # right signature, another window
    u.sendto((body + ":" + "0" * 64).encode(), ("127.0.0.1", EVENT_PORT))                                                              # bad signature
    u.sendto(b"junk", ("127.0.0.1", EVENT_PORT))
    time.sleep(0.5)
    check(b.last().get("pulses", 0) == 0, f"forged events are ignored: {b.last()}")
    fin = b.wait_state("final", 25)
    check(fin is not None and fin["pulses"] == 1, f"only the real coin counted: {fin}")
    b.close()
    for ctlx, label in [({"events": False}, "a box without coin events"), ({"drop_events": True}, "lost coin events")]:
        env.reset_device(MAC_B)
        env.set_box(busy=False, coins_at=[0.5], **ctlx)
        b = Cust("127.0.0.2", reset=True)
        b.wait_state("idle", 5)
        b.mark()
        b.send({"t": "start", "plan": "hyper"})
        fin = b.wait_state("final", 30)
        check(fin is not None and fin["pulses"] == 1 and fin["online"] is True, f"{label}: still counted by the signed checks: {fin}")
        b.close()

    # ---- the page can be closed in the middle of a window: the result is waiting when it comes back ----------------------------------------
    env.reset_device(MAC_B)
    env.set_box(busy=False, coins_at=[0.4, 0.8])
    b = Cust("127.0.0.2", reset=True)
    b.wait_state("idle", 5)
    b.mark()
    b.send({"t": "start", "plan": "hyper"})
    b.wait(lambda m: m.get("s") == "armed" and m.get("pulses", 0) >= 1, 8)
    b.close()
    time.sleep(8)
    b = Cust("127.0.0.2")
    s = b.wait(lambda m: m.get("s") in ("final", "idle"), 5)
    check(s is not None and s["s"] == "final" and s["pulses"] == 2 and s["online"] is True, f"a sleeping or closed phone loses nothing: {s}")
    b.close()

    # ---- the router restarts in the middle of a window: the coins are credited once, from the flash record ----------------------------------
    env.reset_device(MAC_C)
    time.sleep(max(0, 22 - (time.time() - 0)) if False else 0)
    env.set_box(busy=False, coins_at=[0.3, 0.5, 0.7])
    e2 = Env(offset=10, EMPTY_COOLDOWN="1")   # a second, clean environment for the restart tests (own box, own data)
    try:
        e2.start()
        e2.nds_client(MAC_C)
        e2.set_box(busy=False, coins_at=[0.3, 0.5, 0.7])
        c = Cust("127.0.0.3", port=e2.PP, reset=True)
        c.wait_state("idle", 5)
        c.send({"t": "start", "plan": "hyper"})
        c.wait(lambda m: m.get("s") == "armed" and m.get("pulses", 0) >= 3, 8)
        sid = [f for f in os.listdir(f"{e2.data}/open")][0]
        e2.portal.send_signal(signal.SIGKILL)   # power cut / crash
        e2.portal.wait()
        e2.portal = None
        c.close()
        check(e2.nds_get(MAC_C)["STATE"] == "Preauthenticated" and e2.roll() == {}, "nothing was granted or recorded before the crash")
        e2.box_call("release", sid)             # the box's own timer ended the window
        time.sleep(1.2)
        e2.start()
        check(wait_until(lambda: MAC_C in e2.roll(), 10), "after the restart the coins the box still holds are credited")
        r = e2.roll()[MAC_C]
        check(r[13] == "3" and r[5] == "18" and e2.revenue().count("\n") == 1, f"once, priced for the whole window: {r} / {e2.revenue()}")
        check(wait_until(lambda: os.listdir(f"{e2.data}/open") == [], 10), "and acknowledged on the box")
        check(any(l.startswith("ack ") for l in e2.boxlines()), "the box saw the acknowledgement")
        e2.stop()
        e2.start()
        time.sleep(2)
        check(e2.revenue().count("\n") == 1 and e2.roll()[MAC_C][5] == "18", "a second restart does not credit it again")
        # a device with paid time that openNDS forgot is put back online when its page opens
        e2.nds_client(MAC_C)
        c = Cust("127.0.0.3", port=e2.PP, reset=True)
        s = c.wait_state("idle", 5)
        check(s is not None and s["online"] is True and s["left"] > 0 and e2.nds_get(MAC_C)["STATE"] == "Authenticated", f"reconnect by MAC after a restart: {s}")
        c.close()
        # recovering the same window twice never credits twice (a recorded window is only acknowledged)
        check(e2.cli("verify")[1].startswith("OK 1 3"), "ledger intact")
    finally:
        e2.close()

    # ---- fair use: HyperSpeed is slowed after the limit, released later; Endurance is never touched -----------------------------------------
    env.reset_device(MAC_D)
    env.set_box(busy=False, coins_at=[0.3, 0.5, 0.7, 0.9, 1.1])
    d = Cust("127.0.0.4", reset=True)
    d.wait_state("idle", 5)
    d.mark()
    d.send({"t": "start", "plan": "hyper"})
    fin = d.wait_state("final", 25)
    check(fin is not None and fin["online"] is True, "a HyperSpeed customer is online")
    d.close()
    env.clear_nds_log()
    nd = env.nds_get(MAC_D)
    env.nds_client(MAC_D, STATE="Authenticated", SESSION_END=nd["SESSION_END"], DL=900, UL=300)
    ok = wait_until(lambda: any(c.startswith("auth " + MAC_D) and " 1000 2000 " in c for c in env.nds_calls()), 8)
    check(ok, "after the limit the connection is slowed (2000 kbit/s down, 1000 up): " + str(env.nds_calls()[-6:]))
    ok = wait_until(lambda: any(c.startswith("auth " + MAC_D) and " 0 0 0 0" in c for c in env.nds_calls()), 8)
    check(ok, "and released again after the throttle period")
    env.reset_device(MAC_A)

    # ---- the operator's tools -------------------------------------------------------------------------------------------------------------
    rc, out = env.cli("box")
    check(rc == 0 and "answers" in out, "box: " + out)
    rc, out = env.cli("reconcile")
    check(rc == 0 and out.startswith("RECONCILE OK"), "reconcile: " + out)
    rc, out = env.cli("report", "7")
    check(rc == 0 and "PHP" in out and "Total last 7 day(s): PHP" in out and "hyper" in out and "endurance" in out, "report: " + out)
    led = open(f"{env.data}/revenue.csv").read()
    first = led.split("\n")[0].split(",")
    first[2] = str(int(first[2]) + 90)
    open(f"{env.data}/revenue.csv", "w").write(",".join(first) + "\n" + "\n".join(led.split("\n")[1:]))
    rc, out = env.cli("verify")
    check(rc != 0 and out == "BAD 1", "an edited ledger line is detected: " + out)
    rc, out = env.cli("reconcile")
    check(rc == 3 and "BADLEDGER" in out, "reconcile reports a broken ledger: " + out)
    open(f"{env.data}/revenue.csv", "w").write(led)
    env.stop()
    rc, out = env.cli("box")
    check(rc == 0, "box check works without the portal running")
    env.start()
    st = env.admin(f"/admin/start?mac={MAC_B}&plan=hyper")
    check(st.get("s") in ("starting", "armed"), f"the local admin interface opens a window (piso-setup test-coin): {st}")
    time.sleep(1)
    check(env.admin(f"/admin/status?mac={MAC_B}").get("s") == "armed", "and reports it")
    env.admin(f"/admin/finish?mac={MAC_B}")
    check(env.admin("/admin/status?mac=zz").get("error") == "NOT_FOUND", "bad requests are refused")

    # ---- robustness -------------------------------------------------------------------------------------------------------------------------
    x = Cust("127.0.0.9")
    check(not x.ok and "403" in x.head, "a device the router does not know gets no coin page: " + x.head[:20])
    g = socket.create_connection(("127.0.0.1", PORTAL_PORT)); g.send(b"\x00\x01garbage\r\n\r\n"); g.close()
    w = Cust("127.0.0.2", reset=True)
    w.send_raw(0x81, b"not json at all")
    w.send_raw(0x81, b'{"t":"start","plan":"nonsense"}')
    w.send_raw(0x82, b"\x00" * 40)
    time.sleep(0.5)
    big = socket.create_connection(("127.0.0.1", PORTAL_PORT), source_address=("127.0.0.2", 0))
    check(env.get("/ping")[1] == "ok", "garbage and bad messages do not take the portal down")
    w.close()
finally:
    env.close()
finish()
