#!/usr/bin/env python3
"""
Turns the dashboard's static files (esp32_firmware/web/*) into gzip-compressed arrays the box serves straight
from flash, writing esp32_firmware/include/WebAssets.h.

  python3 scripts/embed_web.py            regenerate the header (do this after editing anything in web/)
  python3 scripts/embed_web.py --check    exit 1 if the header is out of date (CI runs this)

The output is reproducible (fixed gzip timestamp), so the check is exact. Each asset gets a version tag taken
from its content hash; the pages link to /assets/<name>?v=<tag>, so browsers cache an asset until it changes.
"""

import gzip
import hashlib
import os
import sys

ROOT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "esp32_firmware")
WEB_DIR = os.path.join(ROOT, "web")
OUT = os.path.join(ROOT, "include", "WebAssets.h")

# file in web/ -> (URL name, content type, C identifier)
ASSETS = [
    ("portal.css", "text/css; charset=utf-8", "PORTAL_CSS"),
    ("portal-core.js", "application/javascript; charset=utf-8", "PORTAL_CORE_JS"),
    ("portal-modals.js", "application/javascript; charset=utf-8", "PORTAL_MODALS_JS"),
    ("superadmin.js", "application/javascript; charset=utf-8", "SUPERADMIN_JS"),
    ("ota.js", "application/javascript; charset=utf-8", "OTA_JS"),
]


def render():
    out = [
        "#ifndef WEB_ASSETS_H",
        "#define WEB_ASSETS_H",
        "",
        "// GENERATED by scripts/embed_web.py from esp32_firmware/web/. Do not edit; edit web/ and regenerate.",
        "#include <stddef.h>",
        "#include <stdint.h>",
        "",
    ]
    table = []
    for name, ctype, ident in ASSETS:
        with open(os.path.join(WEB_DIR, name), "rb") as f:
            raw = f.read()
        gz = bytearray(gzip.compress(raw, compresslevel=9, mtime=0))
        # Python 3.13 writes 255 ("unknown") in the header's OS byte where 3.11 and 3.12 write 3 ("Unix"); the
        # compressed data is the same. Pin it so the header is byte-for-byte the same on every Python version.
        gz[9] = 3
        gz = bytes(gz)
        tag = hashlib.sha256(raw).hexdigest()[:12]
        body = ",".join(str(b) for b in gz)
        out.append(f"// {name}: {len(raw)} bytes, {len(gz)} gzipped")
        out.append(f"static const uint8_t {ident}_GZ[] = {{{body}}};")
        out.append(f'static const char {ident}_V[] = "{tag}";')
        out.append("")
        table.append((name, ctype, ident))
    out.append("struct WebAsset {")
    out.append("    const char* name;")
    out.append("    const char* contentType;")
    out.append("    const uint8_t* gz;")
    out.append("    size_t gzLen;")
    out.append("    const char* version;")
    out.append("};")
    out.append("")
    out.append("static const WebAsset WEB_ASSETS[] = {")
    for name, ctype, ident in table:
        out.append(f'    {{"{name}", "{ctype}", {ident}_GZ, sizeof({ident}_GZ), {ident}_V}},')
    out.append("};")
    out.append("static const size_t WEB_ASSET_COUNT = sizeof(WEB_ASSETS) / sizeof(WEB_ASSETS[0]);")
    out.append("")
    out.append("#endif // WEB_ASSETS_H")
    return "\n".join(out) + "\n"


def main():
    text = render()
    if "--check" in sys.argv:
        current = open(OUT, encoding="utf-8").read() if os.path.exists(OUT) else ""
        if current != text:
            print("WebAssets.h is out of date: run python3 scripts/embed_web.py and commit the result.")
            sys.exit(1)
        print("WebAssets.h is up to date.")
        return
    with open(OUT, "w", encoding="utf-8", newline="\n") as f:
        f.write(text)
    print(f"Wrote {OUT}")


if __name__ == "__main__":
    main()
