#!/usr/bin/env python3
"""
PisoPhone slot license tool (owner only; needs `pip install cryptography`).

Licenses are signed with YOUR private key and checked by the box with the public key built into
its firmware, so a box can verify a license but nobody without the private key can make one.
Keep the private key offline. Never commit it, never put it in CI.

One-time setup:
  python3 scripts/generate_license.py keygen --private ~/pisophone_license_key.pem
  (this also rewrites esp32_firmware/include/LicensePubKey.h; rebuild and flash the boxes)

Issue a license for a box (use the code shown in the box dashboard, or just its MAC):
  python3 scripts/generate_license.py issue --private ~/pisophone_license_key.pem \
      --code PISO-AABBCCDDEEFF-1-6-8F3A --slots 3
  python3 scripts/generate_license.py issue --private KEY.pem --mac AA:BB:CC:DD:EE:FF --slots 3

Token format: PISOLIC1.<MAC>.<slots>.<base64 ECDSA P-256 signature of
"pisophone-license-v1|<MAC>|<slots>">. Paste it into the dashboard's license box.
"""

import argparse
import base64
import hashlib
import os
import sys

MAX_SUPPORTED_SLOTS = 6
PUBKEY_HEADER = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "esp32_firmware", "include",
                             "LicensePubKey.h")
ROUTER_KEY_FILE = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "tools", "pisoportal", "owner_key.b64")


def _crypto():
    try:
        from cryptography.hazmat.primitives import hashes, serialization
        from cryptography.hazmat.primitives.asymmetric import ec
    except ImportError:
        sys.exit("This tool needs the 'cryptography' package: pip install cryptography")
    return hashes, serialization, ec


def clean_mac(mac: str) -> str:
    cleaned = "".join(c for c in mac.upper() if c in "0123456789ABCDEF")
    if len(cleaned) != 12:
        raise ValueError(f"not a MAC address: {mac!r}")
    return cleaned


def request_checksum(mac_clean: str, current: int, maximum: int) -> str:
    """The 4-character check at the end of a Box Request Code. It only catches typing mistakes."""
    payload = f"BOXREQ:{mac_clean}:{current}:{maximum}"
    return hashlib.sha256(payload.encode()).hexdigest().upper()[:4]


def parse_request_code(code: str):
    """PISO-<MAC>-<CURRENT>-<MAX>-<CHECK>, or a bare MAC. Returns (mac_clean, current, max)."""
    parts = code.strip().upper().split("-")
    if len(parts) >= 4 and parts[0] in ("PISO", "PISOBX", "BOX"):
        mac = clean_mac(parts[1])
        current, maximum = int(parts[2]), int(parts[3])
        if len(parts) >= 5 and parts[4] != request_checksum(mac, current, maximum):
            raise ValueError("request code checksum does not match; check how it was typed")
        return mac, current, maximum
    return clean_mac(code), 1, MAX_SUPPORTED_SLOTS


def load_private(path: str):
    _, serialization, _ = _crypto()
    with open(path, "rb") as f:
        return serialization.load_pem_private_key(f.read(), password=None)


def make_token(private_key, mac: str, slots: int) -> str:
    hashes, _, ec = _crypto()
    mac = clean_mac(mac)
    if not 1 <= slots <= MAX_SUPPORTED_SLOTS:
        raise ValueError(f"slots must be 1..{MAX_SUPPORTED_SLOTS}")
    message = f"pisophone-license-v1|{mac}|{slots}".encode()
    sig = private_key.sign(message, ec.ECDSA(hashes.SHA256()))
    return f"PISOLIC1.{mac}.{slots}.{base64.b64encode(sig).decode()}"


def write_router_key(public_key, path: str = ROUTER_KEY_FILE):
    """The same public key for the router program (tools/pisoportal/owner_key.b64): routers install only updates this key signed."""
    _, serialization, _ = _crypto()
    der = public_key.public_bytes(serialization.Encoding.DER, serialization.PublicFormat.SubjectPublicKeyInfo)
    with open(path, "w") as f:
        f.write(base64.b64encode(der).decode() + "\n")


def write_pubkey_header(public_key, path: str):
    _, serialization, _ = _crypto()
    der = public_key.public_bytes(serialization.Encoding.DER, serialization.PublicFormat.SubjectPublicKeyInfo)
    if os.path.realpath(path) == os.path.realpath(PUBKEY_HEADER):
        write_router_key(public_key)   # (not when a test or another header is the target)
    body = ", ".join(f"0x{b:02x}" for b in der)
    with open(path, "w") as f:
        f.write("#ifndef LICENSE_PUB_KEY_H\n#define LICENSE_PUB_KEY_H\n\n"
                "// Generated by scripts/generate_license.py keygen. Public key only.\n"
                "// DER SubjectPublicKeyInfo of the ECDSA P-256 key that signs slot licenses.\n"
                "#include <stddef.h>\n#include <stdint.h>\n\n"
                f"static const uint8_t LICENSE_PUBKEY_DER[] = {{{body}}};\n"
                "static const size_t LICENSE_PUBKEY_LEN = sizeof(LICENSE_PUBKEY_DER);\n\n"
                "#endif\n")


def cmd_keygen(args):
    hashes, serialization, ec = _crypto()
    if os.path.exists(args.private) and not args.force:
        sys.exit(f"{args.private} already exists; refusing to overwrite it (use --force to replace it)")
    key = ec.generate_private_key(ec.SECP256R1())
    fd = os.open(args.private, os.O_WRONLY | os.O_CREAT | os.O_TRUNC, 0o600)
    with os.fdopen(fd, "wb") as f:
        f.write(key.private_bytes(serialization.Encoding.PEM, serialization.PrivateFormat.PKCS8,
                                  serialization.NoEncryption()))
    write_pubkey_header(key.public_key(), args.header)
    print(f"Private key written to {args.private} (keep it offline and back it up).")
    print(f"Public key written to {args.header}. Rebuild and flash the boxes to use it.")


def cmd_issue(args):
    try:
        if args.code:
            mac, current, maximum = parse_request_code(args.code)
        else:
            mac, current, maximum = clean_mac(args.mac), 1, MAX_SUPPORTED_SLOTS
        slots = args.slots
        if slots > maximum:
            print(f"Warning: {slots} slots is above this box's limit of {maximum}; the box will refuse it.")
        token = make_token(load_private(args.private), mac, slots)
    except (ValueError, OSError) as e:
        sys.exit(f"Error: {e}")
    print(f"Box MAC       : {':'.join(mac[i:i + 2] for i in range(0, 12, 2))}")
    print(f"Current slots : {current}   Target slots: {slots}")
    print("License (paste into the dashboard):")
    print(token)


def main():
    p = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    sub = p.add_subparsers(dest="cmd", required=True)

    k = sub.add_parser("keygen", help="create the signing key pair (once)")
    k.add_argument("--private", required=True, help="where to write the private key (PEM)")
    k.add_argument("--header", default=PUBKEY_HEADER, help="firmware header to write the public key into")
    k.add_argument("--force", action="store_true", help="replace an existing private key file")
    k.set_defaults(func=cmd_keygen)

    i = sub.add_parser("issue", help="sign a license for one box")
    i.add_argument("--private", required=True, help="private key (PEM) made by keygen")
    g = i.add_mutually_exclusive_group(required=True)
    g.add_argument("--code", help="Box Request Code, e.g. PISO-AABBCCDDEEFF-1-6-8F3A")
    g.add_argument("--mac", help="box MAC address")
    i.add_argument("--slots", type=int, required=True, help="total slots to license (1-6)")
    i.set_defaults(func=cmd_issue)

    args = p.parse_args()
    args.func(args)


if __name__ == "__main__":
    main()
