#!/usr/bin/env python3
"""
Creates the CARD signing key used to print QR cards. Run it on YOUR computer. Needs: pip install cryptography

  python3 scripts/make_card_key.py                 key saved to ~/pisophone_card_key.pem
  python3 scripts/make_card_key.py /path/key.pem   key saved elsewhere (not inside this repository)

This is a different key from the firmware owner key on purpose: you load the card key every time you print a batch, so it
should not be the key that can sign firmware updates. If the card key leaks, someone can print free time cards (replace it
and reflash the boxes); they still cannot ship firmware.

It refuses to overwrite an existing key, writes only the PUBLIC key into esp32_firmware/include/CardPubKey.h (commit that,
then rebuild and flash every box), and proves the key works by signing and verifying a test card. Until a public key is built
in, boxes reject every card.
"""

import argparse
import os
import stat
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
sys.path.insert(0, HERE)
import card_format  # noqa: E402

DEFAULT_KEY = os.path.join(os.path.expanduser("~"), "pisophone_card_key.pem")
HEADER = os.path.join(ROOT, "esp32_firmware", "include", "CardPubKey.h")


def inside_repo(path):
    real = os.path.normcase(os.path.realpath(path))
    root = os.path.normcase(os.path.realpath(ROOT))
    return real == root or real.startswith(root + os.sep)


def write_header(public_key, path):
    from cryptography.hazmat.primitives import serialization
    der = public_key.public_bytes(serialization.Encoding.DER, serialization.PublicFormat.SubjectPublicKeyInfo)
    body = ", ".join(f"0x{b:02x}" for b in der)
    with open(path, "w") as f:
        f.write("#ifndef CARD_PUB_KEY_H\n#define CARD_PUB_KEY_H\n\n"
                "// Generated by scripts/make_card_key.py. Public key only.\n"
                "// DER SubjectPublicKeyInfo of the ECDSA P-256 key that signs QR cards (scripts/make_cards.py).\n"
                "#include <stddef.h>\n#include <stdint.h>\n\n"
                "// clang-format off\n"
                f"static const uint8_t CARD_PUBKEY_DER[] = {{{body}}};\n"
                "// clang-format on\n"
                "static const size_t CARD_PUBKEY_LEN = sizeof(CARD_PUBKEY_DER);\n\n"
                "#endif\n")


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("path", nargs="?", default=DEFAULT_KEY, help="where to save the private key")
    ap.add_argument("--header", default=HEADER, help="firmware header that receives the public key")
    a = ap.parse_args()
    try:
        from cryptography.hazmat.primitives import serialization
        from cryptography.hazmat.primitives.asymmetric import ec
    except ImportError:
        sys.exit("This tool needs the 'cryptography' package: pip install cryptography")

    if inside_repo(a.path):
        sys.exit(f"Refusing: {a.path} is inside the repository ({ROOT}). Pick a folder outside it.")
    if os.path.exists(a.path):
        sys.exit(f"Refusing to overwrite {a.path}. Move it away first if you really want a new key (every printed card stops working).")

    key = ec.generate_private_key(ec.SECP256R1())
    pem = key.private_bytes(serialization.Encoding.PEM, serialization.PrivateFormat.PKCS8, serialization.NoEncryption())
    card = card_format.encode(key, "aabbccddeeff", 1, 10800)
    if not card_format.verify(key.public_key(), card):
        sys.exit("Self-test FAILED: the key could not sign and verify a test card.")
    print("Self-test passed (signed and verified a test card).")

    fd = os.open(a.path, os.O_WRONLY | os.O_CREAT | os.O_EXCL, stat.S_IRUSR | stat.S_IWUSR)
    with os.fdopen(fd, "wb") as f:
        f.write(pem)
    write_header(key.public_key(), a.header)
    print(f"""
Private card key saved to {a.path}. Back it up in two offline places: lose it and you cannot print more cards for boxes
that have its public key; leak it and anyone can print free time.
Public key written to {a.header}.
Next: git add esp32_firmware/include/CardPubKey.h && git commit -m "Install card public key", then rebuild and flash the boxes.""")


if __name__ == "__main__":
    main()
