"""
Shared owner-key helpers for sign_firmware.py, sign_router.py and make_owner_keys.py (needs `pip install cryptography`).

One ECDSA P-256 key signs firmware and router updates. Boxes and routers check those signatures with the public key
built into esp32_firmware/include/LicensePubKey.h (the file name is historical) and tools/pisoportal/owner_key.b64.
Keep the private key offline. Never commit it, never put it in CI.
"""

import base64
import os
import sys

PUBKEY_HEADER = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "esp32_firmware", "include",
                             "LicensePubKey.h")
ROUTER_KEY_FILE = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "tools", "pisoportal", "owner_key.b64")


def _crypto():
    try:
        from cryptography.hazmat.primitives import hashes, serialization
        from cryptography.hazmat.primitives.asymmetric import ec
    except ImportError:
        sys.exit("This tool needs the 'cryptography' package: pip install cryptography")
    return hashes, serialization, ec


def load_private(path: str):
    _, serialization, _ = _crypto()
    with open(path, "rb") as f:
        return serialization.load_pem_private_key(f.read(), password=None)


def write_router_key(public_key, path: str = ROUTER_KEY_FILE):
    """The same public key for the router program (tools/pisoportal/owner_key.b64): routers install only updates this key signed."""
    _, serialization, _ = _crypto()
    der = public_key.public_bytes(serialization.Encoding.DER, serialization.PublicFormat.SubjectPublicKeyInfo)
    with open(path, "w") as f:
        f.write(base64.b64encode(der).decode() + "\n")


def write_pubkey_header(public_key, path: str):
    _, serialization, _ = _crypto()
    der = public_key.public_bytes(serialization.Encoding.DER, serialization.PublicFormat.SubjectPublicKeyInfo)
    if os.path.realpath(path) == os.path.realpath(PUBKEY_HEADER):
        write_router_key(public_key)   # (not when a test or another header is the target)
    body = ", ".join(f"0x{b:02x}" for b in der)
    with open(path, "w") as f:
        f.write("#ifndef LICENSE_PUB_KEY_H\n#define LICENSE_PUB_KEY_H\n\n"
                "// Generated by scripts/make_owner_keys.py. Public key only.\n"
                "// DER SubjectPublicKeyInfo of the ECDSA P-256 key that signs firmware updates.\n"
                "#include <stddef.h>\n#include <stdint.h>\n\n"
                f"static const uint8_t LICENSE_PUBKEY_DER[] = {{{body}}};\n"
                "static const size_t LICENSE_PUBKEY_LEN = sizeof(LICENSE_PUBKEY_DER);\n\n"
                "#endif\n")
