#!/usr/bin/env python3
"""Manage the remotely distributed PisoPhone super-admin password.

The ESP32s download website/update/credentials.json, check that it is signed with your private
key, and then accept the new super-admin password. The website only ever holds a salted PBKDF2
hash, never the password.

One-time setup (keep the private key OFFLINE, never commit it):
    python3 scripts/superadmin_credentials.py keygen --private ~/pisophone-superadmin.key
  This writes the private key and esp32_firmware/include/SuperAdminPubKey.h. Rebuild and flash
  the firmware once with that header.

Rotate the password (any time, e.g. after a leak):
    python3 scripts/superadmin_credentials.py set --private ~/pisophone-superadmin.key
  Prints a new random password once and updates website/update/credentials.json. Commit and
  merge that file to main; every ESP32 with internet picks it up within about an hour.
  Use --password to choose your own instead (a long passphrase, since the hash is public).

Needs:  pip install cryptography
"""
import argparse
import base64
import hashlib
import json
import os
import secrets
import sys

from cryptography.hazmat.primitives import hashes, serialization
from cryptography.hazmat.primitives.asymmetric import ec

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
CRED_JSON = os.path.join(REPO, "website", "update", "credentials.json")
PUBKEY_HEADER = os.path.join(REPO, "esp32_firmware", "include", "SuperAdminPubKey.h")
DEFAULT_ITERATIONS = 10000
MIN_PASSWORD_LEN = 12


def canonical(version, iterations, salt_hex, hash_hex):
    # Must match credcrypto::canonicalMessage() in esp32_firmware/include/CredCrypto.h.
    return f"pisophone-superadmin-v1|{version}|{iterations}|{salt_hex}|{hash_hex}"


def make_credentials(private_key, password, version, iterations=DEFAULT_ITERATIONS):
    salt = secrets.token_bytes(16)
    digest = hashlib.pbkdf2_hmac("sha256", password.encode("utf-8"), salt, iterations, 32)
    salt_hex, hash_hex = salt.hex(), digest.hex()
    sig = private_key.sign(canonical(version, iterations, salt_hex, hash_hex).encode(),
                           ec.ECDSA(hashes.SHA256()))
    return {"version": version, "iter": iterations, "salt": salt_hex, "hash": hash_hex,
            "sig": base64.b64encode(sig).decode()}


def write_pubkey_header(public_key, path):
    der = public_key.public_bytes(serialization.Encoding.DER,
                                  serialization.PublicFormat.SubjectPublicKeyInfo)
    body = ", ".join(f"0x{b:02x}" for b in der)
    with open(path, "w") as f:
        f.write("#ifndef SUPER_ADMIN_PUB_KEY_H\n#define SUPER_ADMIN_PUB_KEY_H\n\n"
                "// Generated by scripts/superadmin_credentials.py keygen. Public key only.\n"
                "// DER SubjectPublicKeyInfo of the ECDSA P-256 key that signs credentials.json.\n"
                "#include <stddef.h>\n#include <stdint.h>\n\n"
                f"static const uint8_t SUPER_ADMIN_PUBKEY_DER[] = {{{body}}};\n"
                "static const size_t SUPER_ADMIN_PUBKEY_LEN = sizeof(SUPER_ADMIN_PUBKEY_DER);\n\n"
                "#endif\n")


def load_private(path):
    with open(path, "rb") as f:
        return serialization.load_pem_private_key(f.read(), password=None)


def cmd_keygen(args):
    if os.path.exists(args.private) and not args.force:
        sys.exit(f"{args.private} already exists; refusing to overwrite (use --force).")
    key = ec.generate_private_key(ec.SECP256R1())
    pem = key.private_bytes(serialization.Encoding.PEM, serialization.PrivateFormat.PKCS8,
                            serialization.NoEncryption())
    fd = os.open(args.private, os.O_WRONLY | os.O_CREAT | os.O_TRUNC, 0o600)
    with os.fdopen(fd, "wb") as f:
        f.write(pem)
    write_pubkey_header(key.public_key(), PUBKEY_HEADER)
    print(f"Private key written to {args.private} (keep it offline and backed up).")
    print(f"Public key header written to {PUBKEY_HEADER}; rebuild and flash the firmware once.")


def cmd_set(args):
    key = load_private(args.private)
    password = args.password or secrets.token_urlsafe(18)
    if len(password) < MIN_PASSWORD_LEN:
        sys.exit(f"Password must be at least {MIN_PASSWORD_LEN} characters (the hash is public).")
    version = 1
    if os.path.exists(CRED_JSON):
        with open(CRED_JSON) as f:
            version = int(json.load(f)["version"]) + 1
    creds = make_credentials(key, password, version, args.iterations)
    with open(CRED_JSON, "w") as f:
        json.dump(creds, f, indent=2)
        f.write("\n")
    print(f"credentials.json updated to version {version}.")
    if not args.password:
        print(f"New super-admin password (shown once): {password}")
    print("Commit and merge website/update/credentials.json to main to roll it out.")


def main():
    p = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    sub = p.add_subparsers(dest="cmd", required=True)
    k = sub.add_parser("keygen", help="create the signing key pair")
    k.add_argument("--private", required=True, help="where to write the private key")
    k.add_argument("--force", action="store_true")
    k.set_defaults(fn=cmd_keygen)
    s = sub.add_parser("set", help="publish a new super-admin password")
    s.add_argument("--private", required=True, help="path to the private key")
    s.add_argument("--password", help="choose the password instead of generating one")
    s.add_argument("--iterations", type=int, default=DEFAULT_ITERATIONS)
    s.set_defaults(fn=cmd_set)
    args = p.parse_args()
    args.fn(args)


if __name__ == "__main__":
    main()
