; PlatformIO Project Configuration File for ESP32-C3 / ESP32 Master Kiosk Firmware
; Framework: Arduino

[env]
board_upload.erase_flash = yes
board_build.filesystem = littlefs
lib_deps =
    bblanchon/ArduinoJson @ ^6.21.3

[platformio]
src_dir = src
include_dir = include
data_dir = data
default_envs = esp32-c3-dev
extra_configs = envs/*.ini
