package com.pisophone.kiosk

import com.pisophone.kiosk.security.HardwareLockManager
import org.junit.Assert.assertTrue
import org.junit.Test

class HardwareLockSignatureTest {
    @Test
    fun testRsaSignatureVerification() {
        val payload = "HW-TEST-1234|1789000000000"
        val signatureBase64Url = "1ONmQ5VHdxS2B9DlwTXMHoNSfm9Ot9rnz3OEzh-bMyZZbuTn_vHMV-hN67mVLu5Yqm3q9fhGPyCLGjCNl3YoY_DSjgPpmoS0heWGrtLnMaZU3iW7wWNVJg-0Om91nwGFi0mNGuFfDNFj7gk6bRulWq2h0HBXndm1FYfPdHPu7Vh_17lgViBI4GCLmEEna5wgFVk4DVr_uteIMgAVlAFlWdmE3FU-QNsjChVQu1B_zNdr1DJtSg7n2VDHTJ6qSMG2_ySrFKv5uZEpV4-0EYifZry2kZkUnJkxVAfDirrwR_MMoS4jOEqOcs3FfWCPIQSnqYTCEbnANIzrr_F_m6QA7w"
        
        val isValid = HardwareLockManager.verifyRsaSignature(payload, signatureBase64Url)
        assertTrue("RSA signature generated by WebCrypto must verify successfully in Android", isValid)
    }
}
